apiVersion: v1
kind: Service
metadata:
  name: grpc-service
  namespace: grpc-cluster
spec:
  selector:
    app: grpc
  ports:
    - name: grpc-server-port
      protocol: TCP
      port: 3001
      targetPort: 3001
    - name: grpc-client-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
