// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: bands.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definición del mensaje Band que representa una banda musical.
type Band struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Album string `protobuf:"bytes,2,opt,name=album,proto3" json:"album,omitempty"`
	Year  string `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
	Rank  int32  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
}

func (x *Band) Reset() {
	*x = Band{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bands_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Band) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Band) ProtoMessage() {}

func (x *Band) ProtoReflect() protoreflect.Message {
	mi := &file_bands_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Band.ProtoReflect.Descriptor instead.
func (*Band) Descriptor() ([]byte, []int) {
	return file_bands_proto_rawDescGZIP(), []int{0}
}

func (x *Band) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Band) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Band) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *Band) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// Definición del mensaje de respuesta BandResponse.
type BandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *BandResponse) Reset() {
	*x = BandResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bands_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BandResponse) ProtoMessage() {}

func (x *BandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bands_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BandResponse.ProtoReflect.Descriptor instead.
func (*BandResponse) Descriptor() ([]byte, []int) {
	return file_bands_proto_rawDescGZIP(), []int{1}
}

func (x *BandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bands_proto protoreflect.FileDescriptor

var file_bands_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x62,
	0x61, 0x6e, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x58, 0x0a, 0x04, 0x42,
	0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x12, 0x0a,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65, 0x61,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x28, 0x0a, 0x0c, 0x42, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x4f, 0x0a, 0x0b, 0x42, 0x61, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40,
	0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12,
	0x2e, 0x62, 0x61, 0x6e, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61,
	0x6e, 0x64, 0x1a, 0x1a, 0x2e, 0x62, 0x61, 0x6e, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x42, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x60, 0x5a, 0x5e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x32,
	0x37, 0x33, 0x30, 0x35, 0x33, 0x38, 0x39, 0x32, 0x30, 0x31, 0x30, 0x31, 0x2f, 0x53, 0x4f, 0x31,
	0x5f, 0x31, 0x53, 0x32, 0x30, 0x32, 0x34, 0x5f, 0x32, 0x30, 0x31, 0x37, 0x30, 0x39, 0x32, 0x38,
	0x32, 0x2f, 0x74, 0x72, 0x65, 0x65, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x79,
	0x65, 0x63, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x79, 0x65, 0x63, 0x74, 0x6f, 0x32, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bands_proto_rawDescOnce sync.Once
	file_bands_proto_rawDescData = file_bands_proto_rawDesc
)

func file_bands_proto_rawDescGZIP() []byte {
	file_bands_proto_rawDescOnce.Do(func() {
		file_bands_proto_rawDescData = protoimpl.X.CompressGZIP(file_bands_proto_rawDescData)
	})
	return file_bands_proto_rawDescData
}

var file_bands_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bands_proto_goTypes = []interface{}{
	(*Band)(nil),         // 0: band_service.Band
	(*BandResponse)(nil), // 1: band_service.BandResponse
}
var file_bands_proto_depIdxs = []int32{
	0, // 0: band_service.BandService.SendBandInfo:input_type -> band_service.Band
	1, // 1: band_service.BandService.SendBandInfo:output_type -> band_service.BandResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bands_proto_init() }
func file_bands_proto_init() {
	if File_bands_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bands_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Band); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bands_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BandResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bands_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bands_proto_goTypes,
		DependencyIndexes: file_bands_proto_depIdxs,
		MessageInfos:      file_bands_proto_msgTypes,
	}.Build()
	File_bands_proto = out.File
	file_bands_proto_rawDesc = nil
	file_bands_proto_goTypes = nil
	file_bands_proto_depIdxs = nil
}
