version: '3'

services:

  # Servicio para la base de datos
  database:
    build:
      context: ./database
    image: carlosmz87/p1_database:latest
    container_name: p1_database_container
    volumes:
      - p1_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - p1_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  # Servicio para el backend
  backend:
    build:
      context: ./backend
    image: carlosmz87/p1_backend:latest
    container_name: p1_backend_container
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - p1_network
    restart: always
    privileged: true
    pid: host
    volumes:
      - /proc:/proc
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - SERVER_PORT=${SERVER_PORT}
    links:
      - database

  # Servicio para el frontend
  frontend:
    build:
      context: ./frontend
    image: carlosmz87/p1_frontend:latest
    container_name: p1_frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - p1_network
    environment:
      - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    links:
      - backend

volumes:
  p1_data:

networks:
  p1_network:
