FROM node:latest as build
WORKDIR /usr/local/app
COPY . .
RUN npm install
CMD ["npm", "run" , "build", "--prod"]
FROM nginx:latest
RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx
COPY --from=build /usr/local/app/build /usr/share/nginx/html
EXPOSE 80