apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: consumer-hpa  # Nombre del HPA
  namespace: p2-cluster  # Namespace donde se encuentra tu deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer-deployment  # Nombre del deployment que deseas escalar
  minReplicas: 2  # Número mínimo de réplicas
  maxReplicas: 5  # Número máximo de réplicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Porcentaje de uso de CPU objetivo
