CREATE TABLE PROCESO (
    ID_PROCESO INT PRIMARY KEY AUTO_INCREMENT,
    PID INT,
    NOMBRE VARCHAR(255),
    ESTADO INT,
    RSS INT,
    UID INT
);

CREATE TABLE PROCESO_HIJO (
    ID_PROCESO_HIJO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PROCESO INT,
    PID INT,
    NOMBRE VARCHAR(255),
    ESTADO INT,
    RSS INT,
    UID INT,
    FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO(ID_PROCESO)
);

CREATE TABLE RAM (
    ID_RAM INT PRIMARY KEY AUTO_INCREMENT,
    TOTAL_MEMORIA INT,
    MEMORIA_LIBRE INT,
    MEMORIA_UTILIZADA INT,
    PORCENTAJE_UTILIZADO FLOAT
);
